/*
# Seed Grand Library formulas — Part 1: Kingdom of Numbers (Quant)

## Plain English
Populates the `formulas` table with ~105 theoretical rules and formulas for
quantitative aptitude topics across all 5 zones of the Kingdom of Numbers.
*/

INSERT INTO formulas (kingdom_id, village_id, topic_name, formula_name, formula_text, description, category, example, tags)
SELECT k.id, v.id, v.name, f.fname, f.ftext, f.fdesc, f.fcat, f.fex, f.ftags
FROM kingdoms k
JOIN villages v ON v.kingdom_id = k.id AND k.slug = 'numbers'
CROSS JOIN (VALUES
  ('Even Number Test', 'n % 2 = 0', 'A number is even if divisible by 2 with no remainder', 'Number System', '14 % 2 = 0, so 14 is even', ARRAY['even','divisibility','parity']),
  ('Odd Number Test', 'n % 2 != 0', 'A number is odd if division by 2 leaves remainder 1', 'Number System', '15 % 2 = 1, so 15 is odd', ARRAY['odd','divisibility','parity']),
  ('Divisibility by 3', 'Sum of digits divisible by 3', 'A number is divisible by 3 if the sum of its digits is divisible by 3', 'Number System', '123: 1+2+3=6, 6/3=2, so 123 is divisible by 3', ARRAY['divisibility','3']),
  ('Divisibility by 4', 'Last two digits divisible by 4', 'A number is divisible by 4 if its last two digits form a number divisible by 4', 'Number System', '1316: 16/4=4, so 1316 is divisible by 4', ARRAY['divisibility','4']),
  ('Divisibility by 5', 'Last digit is 0 or 5', 'A number is divisible by 5 if it ends in 0 or 5', 'Number System', '235 ends in 5, so divisible by 5', ARRAY['divisibility','5']),
  ('Divisibility by 6', 'Divisible by both 2 and 3', 'A number is divisible by 6 if it is divisible by both 2 and 3', 'Number System', '72: even and 7+2=9 divisible by 3', ARRAY['divisibility','6']),
  ('Divisibility by 8', 'Last three digits divisible by 8', 'A number is divisible by 8 if its last three digits form a number divisible by 8', 'Number System', '3712: 712/8=89, so divisible', ARRAY['divisibility','8']),
  ('Divisibility by 9', 'Sum of digits divisible by 9', 'A number is divisible by 9 if the sum of its digits is divisible by 9', 'Number System', '459: 4+5+9=18, 18/9=2', ARRAY['divisibility','9']),
  ('Divisibility by 11', 'Alternating digit sum divisible by 11', 'Subtract and add digits alternately; result divisible by 11', 'Number System', '121: 1-2+1=0, divisible by 11', ARRAY['divisibility','11']),
  ('HCF via Euclid', 'HCF(a,b) = HCF(b, a mod b)', 'Euclidean algorithm for highest common factor', 'Number System', 'HCF(48,18)=HCF(18,12)=HCF(12,6)=6', ARRAY['hcf','euclid','gcd']),
  ('LCM x HCF', 'a x b = HCF(a,b) x LCM(a,b)', 'Product of two numbers equals product of their HCF and LCM', 'Number System', 'For 12,18: HCF=6, LCM=36, 12*18=216=6*36', ARRAY['lcm','hcf','product']),
  ('Remainder Theorem', '(a+b) mod n = ((a mod n)+(b mod n)) mod n', 'Remainder of sum equals sum of remainders mod n', 'Number System', '(17+13) mod 5 = (2+3) mod 5 = 0', ARRAY['remainder','modular']),
  ('Cyclicity of 2', 'Unit digit cycles 2,4,8,6 every 4 powers', 'Powers of 2 cycle unit digit with period 4', 'Number System', '2^1=2, 2^2=4, 2^3=8, 2^4=16, 2^5=32', ARRAY['cyclicity','unit-digit','powers']),
  ('Cyclicity of 3', 'Unit digit cycles 3,9,7,1 every 4 powers', 'Powers of 3 cycle unit digit with period 4', 'Number System', '3^1=3, 3^2=9, 3^3=27, 3^4=81', ARRAY['cyclicity','unit-digit','powers']),
  ('Cyclicity of 7', 'Unit digit cycles 7,9,3,1 every 4 powers', 'Powers of 7 cycle unit digit with period 4', 'Number System', '7^1=7, 7^2=49, 7^3=343, 7^4=2401', ARRAY['cyclicity','unit-digit','powers']),
  ('Number of Factors', 'Product of (exponent+1) for each prime factor', 'If n = p^a * q^b, number of factors = (a+1)(b+1)', 'Number System', '12 = 2^2 * 3^1, factors = (2+1)(1+1) = 6', ARRAY['factors','prime']),
  ('Sum of Factors', 'Product of (p^(a+1)-1)/(p-1) for each prime', 'Sum of all factors formula', 'Number System', '12: ((2^3-1)/1)*((3^2-1)/2) = 7*4 = 28', ARRAY['factors','sum','prime']),
  ('Sum of First N Natural Numbers', 'N(N+1)/2', 'Triangular number formula', 'Number System', 'Sum 1..100 = 100*101/2 = 5050', ARRAY['sum','series','natural']),
  ('Sum of First N Squares', 'N(N+1)(2N+1)/6', 'Sum of squares of first n natural numbers', 'Number System', 'Sum 1^2..5^2 = 5*6*11/6 = 55', ARRAY['sum','squares','series']),
  ('Sum of First N Cubes', '(N(N+1)/2)^2', 'Sum of cubes equals square of triangular number', 'Number System', 'Sum 1^3..4^3 = (4*5/2)^2 = 100', ARRAY['sum','cubes','series']),
  ('Percentage to Fraction', 'p% = p/100', 'Convert percentage to fraction by dividing by 100', 'Arithmetic', '25% = 25/100 = 1/4', ARRAY['percentage','fraction']),
  ('Percentage Change', '((new - old)/old) x 100', 'Percentage increase or decrease formula', 'Arithmetic', 'From 80 to 100: (20/80)*100 = 25% increase', ARRAY['percentage','change']),
  ('Successive Percentage', 'a + b + (ab/100)', 'Net effect of two successive percentage changes', 'Arithmetic', '10% then 20%: 10+20+200/100 = 32%', ARRAY['percentage','successive']),
  ('Ratio Simplification', 'Divide both terms by their HCF', 'Simplify a ratio by dividing both terms by HCF', 'Arithmetic', '24:36 -> HCF=12 -> 2:3', ARRAY['ratio','hcf']),
  ('Combining Ratios', 'Make the common term equal then combine', 'Combine two ratios by equating the common term', 'Arithmetic', 'a:b=2:3, b:c=4:5 -> a:b:c=8:12:15', ARRAY['ratio','combine']),
  ('Proportion Property', 'a:b :: c:d means a*d = b*c', 'In a proportion, product of means equals product of extremes', 'Arithmetic', '2:3 :: 4:6 -> 2*6 = 3*4 = 12', ARRAY['proportion']),
  ('Partnership Profit', 'Profit ratio = Investment x Time', 'Profits shared in ratio of investment multiplied by time', 'Arithmetic', 'A 1000 for 12mo, B 2000 for 6mo -> 1:1', ARRAY['partnership','profit']),
  ('Profit Percentage', '((SP - CP)/CP) x 100', 'Profit percentage on cost price', 'Arithmetic', 'CP=100, SP=120 -> (20/100)*100 = 20%', ARRAY['profit-loss','percentage']),
  ('Loss Percentage', '((CP - SP)/CP) x 100', 'Loss percentage on cost price', 'Arithmetic', 'CP=100, SP=80 -> (20/100)*100 = 20%', ARRAY['profit-loss','percentage']),
  ('Marked Price Relation', 'SP = MP - Discount', 'Selling price equals marked price minus discount', 'Arithmetic', 'MP=200, Discount=30 -> SP=170', ARRAY['marked-price','discount']),
  ('Discount Percentage', '(Discount/MP) x 100', 'Discount as percentage of marked price', 'Arithmetic', 'Discount=30, MP=200 -> 15%', ARRAY['discount','percentage']),
  ('Single Equivalent Discount', 'a + b - (ab/100)', 'Single discount equivalent to two successive discounts', 'Arithmetic', '10%+20% -> 28%', ARRAY['discount','successive']),
  ('Simple Interest', 'SI = (P x R x T)/100', 'Simple interest formula', 'Arithmetic', 'P=1000, R=5%, T=2 -> SI=100', ARRAY['simple-interest','interest']),
  ('Amount with SI', 'A = P + SI = P(1 + RT/100)', 'Total amount with simple interest', 'Arithmetic', 'P=1000, R=5, T=2 -> A=1100', ARRAY['simple-interest','amount']),
  ('Compound Interest', 'A = P(1 + R/100)^T', 'Amount with compound interest', 'Arithmetic', 'P=1000, R=10, T=2 -> A=1210', ARRAY['compound-interest','interest']),
  ('CI Half-Yearly', 'A = P(1 + R/200)^(2T)', 'Compound interest compounded half-yearly', 'Arithmetic', 'P=1000, R=10, T=1 -> 1102.5', ARRAY['compound-interest','half-yearly']),
  ('CI Quarterly', 'A = P(1 + R/400)^(4T)', 'Compound interest compounded quarterly', 'Arithmetic', 'Quarterly compounding formula', ARRAY['compound-interest','quarterly']),
  ('Average Formula', 'Average = Sum of values / Count', 'Arithmetic mean', 'Arithmetic', 'Avg of 10,20,30 = 60/3 = 20', ARRAY['average','mean']),
  ('Weighted Average', 'Sum(value x weight) / Sum(weights)', 'Weighted arithmetic mean', 'Arithmetic', 'Values 10,20 weights 2,3 -> (20+60)/5 = 16', ARRAY['average','weighted']),
  ('Average of Averages', 'Combined avg = (n1*a1 + n2*a2)/(n1+n2)', 'Combine two groups averages', 'Arithmetic', 'Group1 avg 10 (n=4), Group2 avg 20 (n=6) -> 16', ARRAY['average','combined']),
  ('Alligation Rule', '(Cheaper qty):(Dearer qty) = (D - M):(M - C)', 'Ratio of quantities in a mixture', 'Arithmetic', 'C=10, D=30, M=20 -> 1:1', ARRAY['alligation','mixture']),
  ('Mixture Replacement', 'Final = Initial x (1 - R/V)^n', 'Pure quantity after n replacements', 'Arithmetic', 'Replace 1/3 of 9L 3 times -> 9*(2/3)^3 = 8/3 L', ARRAY['mixture','replacement']),
  ('Work Rate', 'Work = Rate x Time', 'Fundamental work formula', 'Speed & Work', 'Rate 1/6 job/hr, 3 hrs -> 1/2 job', ARRAY['work','rate']),
  ('Combined Work', '1/T = 1/A + 1/B', 'Time for two workers together', 'Speed & Work', 'A=6hr, B=12hr -> T=4', ARRAY['work','combined']),
  ('Efficiency Ratio', 'Efficiency = 1/Time', 'Efficiency is inverse of time taken', 'Speed & Work', 'A takes 6hr, B takes 3hr -> eff 1:2', ARRAY['work','efficiency']),
  ('Speed Distance Time', 'Distance = Speed x Time', 'Fundamental motion formula', 'Speed & Work', '60 km/h x 2.5 h = 150 km', ARRAY['speed','distance','time']),
  ('Average Speed', '2 x S1 x S2 / (S1 + S2)', 'Average speed for equal distances', 'Speed & Work', 'S1=60, S2=40 -> 48 km/h', ARRAY['speed','average']),
  ('Relative Speed Same Direction', '|S1 - S2|', 'Relative speed when moving same direction', 'Speed & Work', 'S1=60, S2=40 -> 20 km/h', ARRAY['relative-speed','same-direction']),
  ('Relative Speed Opposite', 'S1 + S2', 'Relative speed when moving toward each other', 'Speed & Work', 'S1=60, S2=40 -> 100 km/h', ARRAY['relative-speed','opposite']),
  ('Boat Downstream', 'Downstream = Boat + Stream', 'Speed with the current', 'Speed & Work', 'Boat 15, Stream 3 -> 18 km/h', ARRAY['boats-streams','downstream']),
  ('Boat Upstream', 'Upstream = Boat - Stream', 'Speed against the current', 'Speed & Work', 'Boat 15, Stream 3 -> 12 km/h', ARRAY['boats-streams','upstream']),
  ('Train Crossing Pole', 'Time = Length / Speed', 'Time for train to pass a stationary point', 'Speed & Work', 'Train 150m at 15 m/s -> 10s', ARRAY['train','pole']),
  ('Train Crossing Platform', 'Time = (Train + Platform) / Speed', 'Time to pass a platform', 'Speed & Work', 'Train 100m, Platform 200m, 20 m/s -> 15s', ARRAY['train','platform']),
  ('Clock Angle', '|30H - 5.5M|', 'Angle between hour and minute hands at H:M', 'Speed & Work', '3:20 -> |90-110| = 20 degrees', ARRAY['clock','angle']),
  ('Clock Hands Coincide', 'Every 65 5/11 minutes', 'Hands coincide 11 times in 12 hours', 'Speed & Work', 'Coincide at ~1:05, 2:10, etc', ARRAY['clock','coincide']),
  ('Calendar Odd Days', 'Odd days = total days mod 7', 'Day of week determined by odd days', 'Speed & Work', '365 mod 7 = 1, so same date next year +1 day', ARRAY['calendar','odd-days']),
  ('Leap Year Test', 'Divisible by 4, not 100 unless 400', 'Leap year rule', 'Speed & Work', '2000 leap, 1900 not', ARRAY['calendar','leap']),
  ('Linear Equation', 'ax + b = 0 -> x = -b/a', 'Solution of linear equation', 'Algebra & Geometry', '3x+6=0 -> x=-2', ARRAY['linear','equation']),
  ('Quadratic Formula', 'x = (-b +/- sqrt(b^2-4ac)) / 2a', 'Roots of ax^2+bx+c=0', 'Algebra & Geometry', 'x^2-5x+6=0 -> x=3 or 2', ARRAY['quadratic','roots']),
  ('Discriminant', 'D = b^2 - 4ac', 'Determines nature of roots', 'Algebra & Geometry', 'D>0 two real, D=0 equal, D<0 complex', ARRAY['quadratic','discriminant']),
  ('Sum of Roots', 'alpha + beta = -b/a', 'Sum of quadratic roots', 'Algebra & Geometry', 'x^2-5x+6 -> sum = 5', ARRAY['quadratic','roots','sum']),
  ('Product of Roots', 'alpha x beta = c/a', 'Product of quadratic roots', 'Algebra & Geometry', 'x^2-5x+6 -> product = 6', ARRAY['quadratic','roots','product']),
  ('Log Product Rule', 'log(mn) = log(m) + log(n)', 'Logarithm of product', 'Algebra & Geometry', 'log(6) = log(2) + log(3)', ARRAY['logarithm','product']),
  ('Log Quotient Rule', 'log(m/n) = log(m) - log(n)', 'Logarithm of quotient', 'Algebra & Geometry', 'log(10/2) = log(10) - log(2)', ARRAY['logarithm','quotient']),
  ('Log Power Rule', 'log(m^n) = n x log(m)', 'Logarithm of a power', 'Algebra & Geometry', 'log(8) = log(2^3) = 3*log(2)', ARRAY['logarithm','power']),
  ('Log Base Change', 'log_b(a) = log_c(a) / log_c(b)', 'Change of base formula', 'Algebra & Geometry', 'log_2(8) = log_10(8)/log_10(2) = 3', ARRAY['logarithm','base-change']),
  ('Index Product Law', 'a^m x a^n = a^(m+n)', 'Multiplication of powers same base', 'Algebra & Geometry', '2^3 x 2^4 = 2^7 = 128', ARRAY['indices','exponents']),
  ('Index Quotient Law', 'a^m / a^n = a^(m-n)', 'Division of powers same base', 'Algebra & Geometry', '2^7 / 2^3 = 2^4 = 16', ARRAY['indices','exponents']),
  ('Index Power Law', '(a^m)^n = a^(mn)', 'Power of a power', 'Algebra & Geometry', '(2^3)^2 = 2^6 = 64', ARRAY['indices','exponents']),
  ('Index Zero Law', 'a^0 = 1 (a != 0)', 'Any non-zero number to power 0 is 1', 'Algebra & Geometry', '5^0 = 1', ARRAY['indices','zero']),
  ('Index Negative Law', 'a^(-n) = 1/a^n', 'Negative exponent', 'Algebra & Geometry', '2^(-3) = 1/8', ARRAY['indices','negative']),
  ('Sum of Angles on Line', '180 degrees', 'Angles on a straight line add to 180', 'Algebra & Geometry', 'Two adjacent angles on a line sum to 180', ARRAY['lines-angles']),
  ('Sum of Triangle Angles', '180 degrees', 'Interior angles of a triangle sum to 180', 'Algebra & Geometry', 'If two angles are 50 and 60, third is 70', ARRAY['triangles','angles']),
  ('Pythagoras Theorem', 'a^2 + b^2 = c^2', 'Right triangle hypotenuse', 'Algebra & Geometry', '3,4,5 triangle: 9+16=25', ARRAY['triangles','pythagoras']),
  ('Triangle Area', 'Area = (1/2) x base x height', 'Area of a triangle', 'Algebra & Geometry', 'base 10, height 6 -> 30', ARRAY['triangles','area']),
  ('Heron Formula', 'Area = sqrt(s(s-a)(s-b)(s-c)), s=(a+b+c)/2', 'Triangle area from sides', 'Algebra & Geometry', 'sides 3,4,5 -> s=6, area=6', ARRAY['triangles','heron','area']),
  ('Circle Circumference', 'C = 2 x pi x r', 'Circumference of circle', 'Algebra & Geometry', 'r=7 -> C=44 (pi=22/7)', ARRAY['circle','circumference']),
  ('Circle Area', 'A = pi x r^2', 'Area of circle', 'Algebra & Geometry', 'r=7 -> A=154', ARRAY['circle','area']),
  ('Sector Area', 'A = (theta/360) x pi x r^2', 'Area of a sector', 'Algebra & Geometry', 'theta=90, r=7 -> 38.5', ARRAY['circle','sector','area']),
  ('Arc Length', 'L = (theta/360) x 2 x pi x r', 'Length of an arc', 'Algebra & Geometry', 'theta=90, r=7 -> 11', ARRAY['circle','arc']),
  ('Rectangle Area', 'A = length x width', 'Area of rectangle', 'Algebra & Geometry', 'l=10, w=5 -> 50', ARRAY['mensuration','rectangle']),
  ('Rectangle Perimeter', 'P = 2(l + w)', 'Perimeter of rectangle', 'Algebra & Geometry', 'l=10, w=5 -> 30', ARRAY['mensuration','rectangle','perimeter']),
  ('Square Area', 'A = side^2', 'Area of square', 'Algebra & Geometry', 'side=6 -> 36', ARRAY['mensuration','square']),
  ('Equilateral Triangle Area', 'A = (sqrt(3)/4) x side^2', 'Area of equilateral triangle', 'Algebra & Geometry', 'side=4 -> 4*sqrt(3)', ARRAY['mensuration','triangle','equilateral']),
  ('Sphere Volume', 'V = (4/3) x pi x r^3', 'Volume of sphere', 'Algebra & Geometry', 'r=3 -> 36*pi', ARRAY['mensuration','sphere','volume']),
  ('Sphere Surface Area', 'A = 4 x pi x r^2', 'Surface area of sphere', 'Algebra & Geometry', 'r=3 -> 36*pi', ARRAY['mensuration','sphere','surface']),
  ('Cylinder Volume', 'V = pi x r^2 x h', 'Volume of cylinder', 'Algebra & Geometry', 'r=3, h=10 -> 90*pi', ARRAY['mensuration','cylinder','volume']),
  ('Cylinder Surface Area', 'A = 2 x pi x r x (r + h)', 'Total surface area of cylinder', 'Algebra & Geometry', 'r=3, h=10 -> 78*pi', ARRAY['mensuration','cylinder','surface']),
  ('Cone Volume', 'V = (1/3) x pi x r^2 x h', 'Volume of cone', 'Algebra & Geometry', 'r=3, h=10 -> 30*pi', ARRAY['mensuration','cone','volume']),
  ('Cube Volume', 'V = side^3', 'Volume of cube', 'Algebra & Geometry', 'side=3 -> 27', ARRAY['mensuration','cube','volume']),
  ('Cube Surface Area', 'A = 6 x side^2', 'Surface area of cube', 'Algebra & Geometry', 'side=3 -> 54', ARRAY['mensuration','cube','surface']),
  ('Permutation nPr', 'nPr = n! / (n-r)!', 'Arrangements of r from n', 'Modern Math', '5P2 = 120/6 = 20', ARRAY['permutation','arrangement']),
  ('Combination nCr', 'nCr = n! / (r!(n-r)!)', 'Selections of r from n', 'Modern Math', '5C2 = 120/(2*6) = 10', ARRAY['combination','selection']),
  ('Combination Symmetry', 'nCr = nC(n-r)', 'Choosing r is same as choosing n-r', 'Modern Math', '10C3 = 10C7', ARRAY['combination','symmetry']),
  ('Factorial', 'n! = n x (n-1) x ... x 1, 0! = 1', 'Factorial definition', 'Modern Math', '5! = 120, 0! = 1', ARRAY['factorial']),
  ('Probability', 'P(E) = Favorable / Total', 'Classical probability', 'Modern Math', '1 die, P(even)=3/6=1/2', ARRAY['probability','classical']),
  ('Complement Rule', 'P(not E) = 1 - P(E)', 'Complement of an event', 'Modern Math', 'P(rain)=0.3 -> P(no rain)=0.7', ARRAY['probability','complement']),
  ('Addition Rule', 'P(A or B) = P(A) + P(B) - P(A and B)', 'Addition rule of probability', 'Modern Math', 'P(A)=0.5, P(B)=0.3, P(A&B)=0.1 -> 0.7', ARRAY['probability','addition']),
  ('Multiplication Rule Independent', 'P(A and B) = P(A) x P(B)', 'Multiplication rule for independent events', 'Modern Math', 'P(A)=0.5, P(B)=0.4 -> 0.2', ARRAY['probability','multiplication','independent']),
  ('DI Percentage from Table', '(Value / Total) x 100', 'Percentage share from data table', 'Modern Math', 'Item 40 of total 200 -> 20%', ARRAY['data-interpretation','percentage']),
  ('DI Growth Rate', '((Current - Previous) / Previous) x 100', 'Growth rate from data', 'Modern Math', 'From 100 to 120 -> 20% growth', ARRAY['data-interpretation','growth']),
  ('DI Average from Table', 'Sum / Count', 'Average from data table values', 'Modern Math', 'Values 20,30,40,50 -> avg 35', ARRAY['data-interpretation','average']),
  ('DI Ratio', 'Value1 / Value2', 'Ratio between two data values', 'Modern Math', 'Sales A=120, B=180 -> 2:3', ARRAY['data-interpretation','ratio']),
  ('Pie Chart Angle', '(Value / Total) x 360', 'Angle for a pie chart slice', 'Modern Math', 'Value 75, Total 300 -> 90 degrees', ARRAY['data-interpretation','pie-chart'])
) AS f(fname, ftext, fdesc, fcat, fex, ftags)
WHERE NOT EXISTS (SELECT 1 FROM formulas fo WHERE fo.village_id = v.id AND fo.formula_name = f.fname);
