/*
# Fix formula deduplication — clear and re-seed with proper village mapping

## Plain English
The previous formula seed used CROSS JOIN which duplicated each formula across
ALL villages in a kingdom. This migration clears all formula rows and re-seeds
them with each formula mapped to its SPECIFIC topic village via a vslug join
key. One row per formula, attached to the correct village.
*/

DELETE FROM formulas;

-- Re-seed Kingdom of Numbers formulas with village slug mapping
INSERT INTO formulas (kingdom_id, village_id, topic_name, formula_name, formula_text, description, category, example, tags)
SELECT k.id, v.id, v.name, f.fname, f.ftext, f.fdesc, f.fcat, f.fex, f.ftags
FROM kingdoms k
JOIN villages v ON v.kingdom_id = k.id AND k.slug = 'numbers'
JOIN (VALUES
  ('numbers-even-numbers', 'Even Number Test', 'n % 2 = 0', 'A number is even if divisible by 2 with no remainder', 'Number System', '14 % 2 = 0, so 14 is even', ARRAY['even','divisibility','parity']),
  ('numbers-odd-numbers', 'Odd Number Test', 'n % 2 != 0', 'A number is odd if division by 2 leaves remainder 1', 'Number System', '15 % 2 = 1, so 15 is odd', ARRAY['odd','divisibility','parity']),
  ('numbers-number-properties', 'Divisibility by 3', 'Sum of digits divisible by 3', 'A number is divisible by 3 if the sum of its digits is divisible by 3', 'Number System', '123: 1+2+3=6, 6/3=2', ARRAY['divisibility','3']),
  ('numbers-divisibility-rules', 'Divisibility by 4', 'Last two digits divisible by 4', 'A number is divisible by 4 if its last two digits form a number divisible by 4', 'Number System', '1316: 16/4=4', ARRAY['divisibility','4']),
  ('numbers-divisibility-rules', 'Divisibility by 5', 'Last digit is 0 or 5', 'A number is divisible by 5 if it ends in 0 or 5', 'Number System', '235 ends in 5', ARRAY['divisibility','5']),
  ('numbers-divisibility-rules', 'Divisibility by 6', 'Divisible by both 2 and 3', 'A number is divisible by 6 if divisible by both 2 and 3', 'Number System', '72: even and 7+2=9 div by 3', ARRAY['divisibility','6']),
  ('numbers-divisibility-rules', 'Divisibility by 8', 'Last three digits divisible by 8', 'A number is divisible by 8 if its last three digits form a number divisible by 8', 'Number System', '3712: 712/8=89', ARRAY['divisibility','8']),
  ('numbers-divisibility-rules', 'Divisibility by 9', 'Sum of digits divisible by 9', 'A number is divisible by 9 if the sum of its digits is divisible by 9', 'Number System', '459: 4+5+9=18', ARRAY['divisibility','9']),
  ('numbers-divisibility-rules', 'Divisibility by 11', 'Alternating digit sum divisible by 11', 'Subtract and add digits alternately', 'Number System', '121: 1-2+1=0', ARRAY['divisibility','11']),
  ('numbers-hcf', 'HCF via Euclid', 'HCF(a,b) = HCF(b, a mod b)', 'Euclidean algorithm for highest common factor', 'Number System', 'HCF(48,18)=6', ARRAY['hcf','euclid','gcd']),
  ('numbers-lcm', 'LCM x HCF', 'a x b = HCF(a,b) x LCM(a,b)', 'Product of two numbers equals product of HCF and LCM', 'Number System', '12*18=216=6*36', ARRAY['lcm','hcf','product']),
  ('numbers-remainders', 'Remainder Theorem', '(a+b) mod n = ((a mod n)+(b mod n)) mod n', 'Remainder of sum equals sum of remainders mod n', 'Number System', '(17+13) mod 5 = 0', ARRAY['remainder','modular']),
  ('numbers-cyclicity', 'Cyclicity of 2', 'Unit digit cycles 2,4,8,6 every 4 powers', 'Powers of 2 cycle unit digit with period 4', 'Number System', '2^1=2, 2^2=4, 2^3=8, 2^4=16', ARRAY['cyclicity','unit-digit','powers']),
  ('numbers-cyclicity', 'Cyclicity of 3', 'Unit digit cycles 3,9,7,1 every 4 powers', 'Powers of 3 cycle unit digit with period 4', 'Number System', '3^1=3, 3^2=9, 3^3=27, 3^4=81', ARRAY['cyclicity','unit-digit','powers']),
  ('numbers-cyclicity', 'Cyclicity of 7', 'Unit digit cycles 7,9,3,1 every 4 powers', 'Powers of 7 cycle unit digit with period 4', 'Number System', '7^1=7, 7^2=49, 7^3=343', ARRAY['cyclicity','unit-digit','powers']),
  ('numbers-factors', 'Number of Factors', 'Product of (exponent+1) for each prime factor', 'If n = p^a * q^b, factors = (a+1)(b+1)', 'Number System', '12 = 2^2 * 3^1, factors = 6', ARRAY['factors','prime']),
  ('numbers-factors', 'Sum of Factors', 'Product of (p^(a+1)-1)/(p-1) for each prime', 'Sum of all factors formula', 'Number System', '12: 7*4 = 28', ARRAY['factors','sum','prime']),
  ('numbers-number-properties', 'Sum of First N Natural Numbers', 'N(N+1)/2', 'Triangular number formula', 'Number System', 'Sum 1..100 = 5050', ARRAY['sum','series','natural']),
  ('numbers-number-properties', 'Sum of First N Squares', 'N(N+1)(2N+1)/6', 'Sum of squares of first n natural numbers', 'Number System', 'Sum 1^2..5^2 = 55', ARRAY['sum','squares','series']),
  ('numbers-number-properties', 'Sum of First N Cubes', '(N(N+1)/2)^2', 'Sum of cubes equals square of triangular number', 'Number System', 'Sum 1^3..4^3 = 100', ARRAY['sum','cubes','series']),
  ('numbers-percentages', 'Percentage to Fraction', 'p% = p/100', 'Convert percentage to fraction', 'Arithmetic', '25% = 1/4', ARRAY['percentage','fraction']),
  ('numbers-percentages', 'Percentage Change', '((new - old)/old) x 100', 'Percentage increase or decrease', 'Arithmetic', '80 to 100: 25% increase', ARRAY['percentage','change']),
  ('numbers-percentages', 'Successive Percentage', 'a + b + (ab/100)', 'Net effect of two successive percentage changes', 'Arithmetic', '10% then 20% = 32%', ARRAY['percentage','successive']),
  ('numbers-ratio', 'Ratio Simplification', 'Divide both terms by their HCF', 'Simplify a ratio by dividing by HCF', 'Arithmetic', '24:36 -> 2:3', ARRAY['ratio','hcf']),
  ('numbers-ratio', 'Combining Ratios', 'Make the common term equal then combine', 'Combine two ratios by equating common term', 'Arithmetic', 'a:b=2:3, b:c=4:5 -> 8:12:15', ARRAY['ratio','combine']),
  ('numbers-proportion', 'Proportion Property', 'a:b :: c:d means a*d = b*c', 'Product of means equals product of extremes', 'Arithmetic', '2:3 :: 4:6 -> 2*6 = 3*4', ARRAY['proportion']),
  ('numbers-partnership', 'Partnership Profit', 'Profit ratio = Investment x Time', 'Profits shared in ratio of investment x time', 'Arithmetic', 'A 1000/12mo, B 2000/6mo -> 1:1', ARRAY['partnership','profit']),
  ('numbers-profit-loss', 'Profit Percentage', '((SP - CP)/CP) x 100', 'Profit percentage on cost price', 'Arithmetic', 'CP=100, SP=120 -> 20%', ARRAY['profit-loss','percentage']),
  ('numbers-profit-loss', 'Loss Percentage', '((CP - SP)/CP) x 100', 'Loss percentage on cost price', 'Arithmetic', 'CP=100, SP=80 -> 20%', ARRAY['profit-loss','percentage']),
  ('numbers-marked-price', 'Marked Price Relation', 'SP = MP - Discount', 'Selling price equals marked price minus discount', 'Arithmetic', 'MP=200, Discount=30 -> SP=170', ARRAY['marked-price','discount']),
  ('numbers-discount', 'Discount Percentage', '(Discount/MP) x 100', 'Discount as percentage of marked price', 'Arithmetic', 'Discount=30, MP=200 -> 15%', ARRAY['discount','percentage']),
  ('numbers-discount', 'Single Equivalent Discount', 'a + b - (ab/100)', 'Single discount equivalent to two successive', 'Arithmetic', '10%+20% -> 28%', ARRAY['discount','successive']),
  ('numbers-simple-interest', 'Simple Interest', 'SI = (P x R x T)/100', 'Simple interest formula', 'Arithmetic', 'P=1000, R=5%, T=2 -> SI=100', ARRAY['simple-interest','interest']),
  ('numbers-simple-interest', 'Amount with SI', 'A = P(1 + RT/100)', 'Total amount with simple interest', 'Arithmetic', 'P=1000, R=5, T=2 -> A=1100', ARRAY['simple-interest','amount']),
  ('numbers-compound-interest', 'Compound Interest', 'A = P(1 + R/100)^T', 'Amount with compound interest', 'Arithmetic', 'P=1000, R=10, T=2 -> A=1210', ARRAY['compound-interest','interest']),
  ('numbers-compound-interest', 'CI Half-Yearly', 'A = P(1 + R/200)^(2T)', 'CI compounded half-yearly', 'Arithmetic', 'P=1000, R=10, T=1 -> 1102.5', ARRAY['compound-interest','half-yearly']),
  ('numbers-compound-interest', 'CI Quarterly', 'A = P(1 + R/400)^(4T)', 'CI compounded quarterly', 'Arithmetic', 'Quarterly compounding', ARRAY['compound-interest','quarterly']),
  ('numbers-averages', 'Average Formula', 'Average = Sum of values / Count', 'Arithmetic mean', 'Arithmetic', 'Avg of 10,20,30 = 20', ARRAY['average','mean']),
  ('numbers-averages', 'Weighted Average', 'Sum(value x weight) / Sum(weights)', 'Weighted arithmetic mean', 'Arithmetic', 'Values 10,20 weights 2,3 -> 16', ARRAY['average','weighted']),
  ('numbers-averages', 'Average of Averages', '(n1*a1 + n2*a2)/(n1+n2)', 'Combine two groups averages', 'Arithmetic', 'Group1 avg 10 (n=4), Group2 avg 20 (n=6) -> 16', ARRAY['average','combined']),
  ('numbers-allegations', 'Alligation Rule', '(Cheaper):(Dearer) = (D-M):(M-C)', 'Ratio of quantities in a mixture', 'Arithmetic', 'C=10, D=30, M=20 -> 1:1', ARRAY['alligation','mixture']),
  ('numbers-mixtures', 'Mixture Replacement', 'Final = Initial x (1 - R/V)^n', 'Pure quantity after n replacements', 'Arithmetic', 'Replace 1/3 of 9L 3x -> 8/3 L', ARRAY['mixture','replacement']),
  ('numbers-time-work', 'Work Rate', 'Work = Rate x Time', 'Fundamental work formula', 'Speed & Work', 'Rate 1/6 job/hr, 3 hrs -> 1/2 job', ARRAY['work','rate']),
  ('numbers-time-work', 'Combined Work', '1/T = 1/A + 1/B', 'Time for two workers together', 'Speed & Work', 'A=6hr, B=12hr -> T=4', ARRAY['work','combined']),
  ('numbers-time-work', 'Efficiency Ratio', 'Efficiency = 1/Time', 'Efficiency is inverse of time', 'Speed & Work', 'A 6hr, B 3hr -> eff 1:2', ARRAY['work','efficiency']),
  ('numbers-time-speed-distance', 'Speed Distance Time', 'Distance = Speed x Time', 'Fundamental motion formula', 'Speed & Work', '60 km/h x 2.5 h = 150 km', ARRAY['speed','distance','time']),
  ('numbers-time-speed-distance', 'Average Speed', '2 x S1 x S2 / (S1 + S2)', 'Average speed for equal distances', 'Speed & Work', 'S1=60, S2=40 -> 48 km/h', ARRAY['speed','average']),
  ('numbers-time-speed-distance', 'Relative Speed Same Direction', '|S1 - S2|', 'Relative speed same direction', 'Speed & Work', '60 and 40 -> 20 km/h', ARRAY['relative-speed']),
  ('numbers-time-speed-distance', 'Relative Speed Opposite', 'S1 + S2', 'Relative speed toward each other', 'Speed & Work', '60 and 40 -> 100 km/h', ARRAY['relative-speed']),
  ('numbers-boats-streams', 'Boat Downstream', 'Downstream = Boat + Stream', 'Speed with the current', 'Speed & Work', 'Boat 15, Stream 3 -> 18', ARRAY['boats-streams','downstream']),
  ('numbers-boats-streams', 'Boat Upstream', 'Upstream = Boat - Stream', 'Speed against the current', 'Speed & Work', 'Boat 15, Stream 3 -> 12', ARRAY['boats-streams','upstream']),
  ('numbers-trains', 'Train Crossing Pole', 'Time = Length / Speed', 'Time for train to pass a point', 'Speed & Work', '150m at 15 m/s -> 10s', ARRAY['train','pole']),
  ('numbers-trains', 'Train Crossing Platform', 'Time = (Train + Platform) / Speed', 'Time to pass a platform', 'Speed & Work', '100m + 200m at 20 m/s -> 15s', ARRAY['train','platform']),
  ('numbers-clocks', 'Clock Angle', '|30H - 5.5M|', 'Angle between hands at H:M', 'Speed & Work', '3:20 -> 20 degrees', ARRAY['clock','angle']),
  ('numbers-clocks', 'Clock Hands Coincide', 'Every 65 5/11 minutes', 'Hands coincide 11 times in 12 hours', 'Speed & Work', '~1:05, 2:10, etc', ARRAY['clock','coincide']),
  ('numbers-calendars', 'Calendar Odd Days', 'Odd days = total days mod 7', 'Day of week from odd days', 'Speed & Work', '365 mod 7 = 1', ARRAY['calendar','odd-days']),
  ('numbers-calendars', 'Leap Year Test', 'Divisible by 4, not 100 unless 400', 'Leap year rule', 'Speed & Work', '2000 leap, 1900 not', ARRAY['calendar','leap']),
  ('numbers-linear-equations', 'Linear Equation', 'ax + b = 0 -> x = -b/a', 'Solution of linear equation', 'Algebra & Geometry', '3x+6=0 -> x=-2', ARRAY['linear','equation']),
  ('numbers-quadratic-equations', 'Quadratic Formula', 'x = (-b +/- sqrt(b^2-4ac)) / 2a', 'Roots of ax^2+bx+c=0', 'Algebra & Geometry', 'x^2-5x+6 -> x=3 or 2', ARRAY['quadratic','roots']),
  ('numbers-quadratic-equations', 'Discriminant', 'D = b^2 - 4ac', 'Determines nature of roots', 'Algebra & Geometry', 'D>0 two real, D=0 equal, D<0 complex', ARRAY['quadratic','discriminant']),
  ('numbers-quadratic-equations', 'Sum of Roots', 'alpha + beta = -b/a', 'Sum of quadratic roots', 'Algebra & Geometry', 'x^2-5x+6 -> sum = 5', ARRAY['quadratic','roots','sum']),
  ('numbers-quadratic-equations', 'Product of Roots', 'alpha x beta = c/a', 'Product of quadratic roots', 'Algebra & Geometry', 'x^2-5x+6 -> product = 6', ARRAY['quadratic','roots','product']),
  ('numbers-logarithms', 'Log Product Rule', 'log(mn) = log(m) + log(n)', 'Logarithm of product', 'Algebra & Geometry', 'log(6) = log(2) + log(3)', ARRAY['logarithm','product']),
  ('numbers-logarithms', 'Log Quotient Rule', 'log(m/n) = log(m) - log(n)', 'Logarithm of quotient', 'Algebra & Geometry', 'log(10/2) = log(10) - log(2)', ARRAY['logarithm','quotient']),
  ('numbers-logarithms', 'Log Power Rule', 'log(m^n) = n x log(m)', 'Logarithm of a power', 'Algebra & Geometry', 'log(8) = 3*log(2)', ARRAY['logarithm','power']),
  ('numbers-logarithms', 'Log Base Change', 'log_b(a) = log_c(a) / log_c(b)', 'Change of base formula', 'Algebra & Geometry', 'log_2(8) = 3', ARRAY['logarithm','base-change']),
  ('numbers-indices', 'Index Product Law', 'a^m x a^n = a^(m+n)', 'Multiplication of powers same base', 'Algebra & Geometry', '2^3 x 2^4 = 2^7', ARRAY['indices','exponents']),
  ('numbers-indices', 'Index Quotient Law', 'a^m / a^n = a^(m-n)', 'Division of powers same base', 'Algebra & Geometry', '2^7 / 2^3 = 2^4', ARRAY['indices','exponents']),
  ('numbers-indices', 'Index Power Law', '(a^m)^n = a^(mn)', 'Power of a power', 'Algebra & Geometry', '(2^3)^2 = 2^6', ARRAY['indices','exponents']),
  ('numbers-indices', 'Index Zero Law', 'a^0 = 1 (a != 0)', 'Any non-zero to power 0 is 1', 'Algebra & Geometry', '5^0 = 1', ARRAY['indices','zero']),
  ('numbers-indices', 'Index Negative Law', 'a^(-n) = 1/a^n', 'Negative exponent', 'Algebra & Geometry', '2^(-3) = 1/8', ARRAY['indices','negative']),
  ('numbers-lines-angles', 'Sum of Angles on Line', '180 degrees', 'Angles on a straight line add to 180', 'Algebra & Geometry', 'Adjacent angles sum to 180', ARRAY['lines-angles']),
  ('numbers-triangles', 'Sum of Triangle Angles', '180 degrees', 'Interior angles of triangle sum to 180', 'Algebra & Geometry', '50+60+70 = 180', ARRAY['triangles','angles']),
  ('numbers-triangles', 'Pythagoras Theorem', 'a^2 + b^2 = c^2', 'Right triangle hypotenuse', 'Algebra & Geometry', '3,4,5: 9+16=25', ARRAY['triangles','pythagoras']),
  ('numbers-triangles', 'Triangle Area', 'Area = (1/2) x base x height', 'Area of a triangle', 'Algebra & Geometry', 'base 10, height 6 -> 30', ARRAY['triangles','area']),
  ('numbers-triangles', 'Heron Formula', 'Area = sqrt(s(s-a)(s-b)(s-c)), s=(a+b+c)/2', 'Triangle area from sides', 'Algebra & Geometry', '3,4,5 -> s=6, area=6', ARRAY['triangles','heron','area']),
  ('numbers-circles', 'Circle Circumference', 'C = 2 x pi x r', 'Circumference of circle', 'Algebra & Geometry', 'r=7 -> C=44', ARRAY['circle','circumference']),
  ('numbers-circles', 'Circle Area', 'A = pi x r^2', 'Area of circle', 'Algebra & Geometry', 'r=7 -> A=154', ARRAY['circle','area']),
  ('numbers-circles', 'Sector Area', 'A = (theta/360) x pi x r^2', 'Area of a sector', 'Algebra & Geometry', 'theta=90, r=7 -> 38.5', ARRAY['circle','sector','area']),
  ('numbers-circles', 'Arc Length', 'L = (theta/360) x 2 x pi x r', 'Length of an arc', 'Algebra & Geometry', 'theta=90, r=7 -> 11', ARRAY['circle','arc']),
  ('numbers-mensuration', 'Rectangle Area', 'A = length x width', 'Area of rectangle', 'Algebra & Geometry', 'l=10, w=5 -> 50', ARRAY['mensuration','rectangle']),
  ('numbers-mensuration', 'Rectangle Perimeter', 'P = 2(l + w)', 'Perimeter of rectangle', 'Algebra & Geometry', 'l=10, w=5 -> 30', ARRAY['mensuration','rectangle','perimeter']),
  ('numbers-mensuration', 'Square Area', 'A = side^2', 'Area of square', 'Algebra & Geometry', 'side=6 -> 36', ARRAY['mensuration','square']),
  ('numbers-mensuration', 'Equilateral Triangle Area', 'A = (sqrt(3)/4) x side^2', 'Area of equilateral triangle', 'Algebra & Geometry', 'side=4 -> 4*sqrt(3)', ARRAY['mensuration','triangle','equilateral']),
  ('numbers-mensuration', 'Sphere Volume', 'V = (4/3) x pi x r^3', 'Volume of sphere', 'Algebra & Geometry', 'r=3 -> 36*pi', ARRAY['mensuration','sphere','volume']),
  ('numbers-mensuration', 'Sphere Surface Area', 'A = 4 x pi x r^2', 'Surface area of sphere', 'Algebra & Geometry', 'r=3 -> 36*pi', ARRAY['mensuration','sphere','surface']),
  ('numbers-mensuration', 'Cylinder Volume', 'V = pi x r^2 x h', 'Volume of cylinder', 'Algebra & Geometry', 'r=3, h=10 -> 90*pi', ARRAY['mensuration','cylinder','volume']),
  ('numbers-mensuration', 'Cylinder Surface Area', 'A = 2 x pi x r x (r + h)', 'Total surface area of cylinder', 'Algebra & Geometry', 'r=3, h=10 -> 78*pi', ARRAY['mensuration','cylinder','surface']),
  ('numbers-mensuration', 'Cone Volume', 'V = (1/3) x pi x r^2 x h', 'Volume of cone', 'Algebra & Geometry', 'r=3, h=10 -> 30*pi', ARRAY['mensuration','cone','volume']),
  ('numbers-mensuration', 'Cube Volume', 'V = side^3', 'Volume of cube', 'Algebra & Geometry', 'side=3 -> 27', ARRAY['mensuration','cube','volume']),
  ('numbers-mensuration', 'Cube Surface Area', 'A = 6 x side^2', 'Surface area of cube', 'Algebra & Geometry', 'side=3 -> 54', ARRAY['mensuration','cube','surface']),
  ('numbers-permutations', 'Permutation nPr', 'nPr = n! / (n-r)!', 'Arrangements of r from n', 'Modern Math', '5P2 = 20', ARRAY['permutation','arrangement']),
  ('numbers-combinations', 'Combination nCr', 'nCr = n! / (r!(n-r)!)', 'Selections of r from n', 'Modern Math', '5C2 = 10', ARRAY['combination','selection']),
  ('numbers-combinations', 'Combination Symmetry', 'nCr = nC(n-r)', 'Choosing r same as choosing n-r', 'Modern Math', '10C3 = 10C7', ARRAY['combination','symmetry']),
  ('numbers-permutations', 'Factorial', 'n! = n x (n-1) x ... x 1, 0! = 1', 'Factorial definition', 'Modern Math', '5! = 120', ARRAY['factorial']),
  ('numbers-probability', 'Probability', 'P(E) = Favorable / Total', 'Classical probability', 'Modern Math', 'P(even on die) = 1/2', ARRAY['probability','classical']),
  ('numbers-probability', 'Complement Rule', 'P(not E) = 1 - P(E)', 'Complement of an event', 'Modern Math', 'P(rain)=0.3 -> P(no rain)=0.7', ARRAY['probability','complement']),
  ('numbers-probability', 'Addition Rule', 'P(A or B) = P(A) + P(B) - P(A and B)', 'Addition rule of probability', 'Modern Math', 'P(A)=0.5, P(B)=0.3, P(A&B)=0.1 -> 0.7', ARRAY['probability','addition']),
  ('numbers-probability', 'Multiplication Rule', 'P(A and B) = P(A) x P(B) for independent', 'Multiplication rule for independent events', 'Modern Math', 'P(A)=0.5, P(B)=0.4 -> 0.2', ARRAY['probability','multiplication']),
  ('numbers-data-interpretation', 'DI Percentage', '(Value / Total) x 100', 'Percentage share from data table', 'Modern Math', '40 of 200 -> 20%', ARRAY['data-interpretation','percentage']),
  ('numbers-data-interpretation', 'DI Growth Rate', '((Current - Previous) / Previous) x 100', 'Growth rate from data', 'Modern Math', '100 to 120 -> 20%', ARRAY['data-interpretation','growth']),
  ('numbers-data-interpretation', 'DI Average', 'Sum / Count', 'Average from data table', 'Modern Math', '20,30,40,50 -> 35', ARRAY['data-interpretation','average']),
  ('numbers-data-interpretation', 'DI Ratio', 'Value1 / Value2', 'Ratio between two data values', 'Modern Math', '120:180 -> 2:3', ARRAY['data-interpretation','ratio']),
  ('numbers-data-interpretation', 'Pie Chart Angle', '(Value / Total) x 360', 'Angle for a pie chart slice', 'Modern Math', '75 of 300 -> 90 degrees', ARRAY['data-interpretation','pie-chart'])
) AS f(vslug, fname, ftext, fdesc, fcat, fex, ftags)
ON v.slug = f.vslug;
